import { Inter } from 'next/font/google'
import Head from 'next/head'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Diets For Your Helth',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <Head>
          <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/animate.css@3.5.2/animate.min.css"/>
          <script defer src="https://unpkg.com/alpinejs@3.2.3/dist/cdn.min.js"></script>
        </Head>

      <body className={inter.className}>{children}</body>
    </html>
  )
}
